{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "control-node.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "telegram-farm" }}
  labels:
    {{- include "control-node.labels" . | nindent 4 }}
{{- end }}


