{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wg-proxy.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "telegram-farm" }}
  labels:
    {{- include "wg-proxy.labels" . | nindent 4 }}
{{- end }}


